version: "3"

services: 
  app:
    build: .
    container_name: sound_voyage_backend
    restart: always
    tty: true
    networks: 
      - sound_voyage_backend_bridge
    ports: 
      - 9000:3000
      - 9229:9229
    volumes: 
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    command: yarn start:dev
    environment:
      NODE_ENV: development
    depends_on: 
      - db

  db: 
    image: mongo:latest
    container_name: sound_voyage_db
    networks:
      - sound_voyage_backend_bridge
    volumes:
      - ./.docker/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: sound_voyage_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks: 
  sound_voyage_backend_bridge:
    driver: bridge